services:
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./index.html:/srv/index.html
      - caddy_data:/data
      - caddy_certs:/config

volumes:
  caddy_data:
  caddy_certs:
